apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prefarm-alert.fullname" . }}
  labels:
    {{- include "prefarm-alert.labels" . | nindent 4 }}
data:
  observer-data.txt: {{ .Values.observerDataB64 }}
  heartbeat_url: {{ .Values.heartbeatURL }}
  alert_url: {{ .Values.alertURL }}
